name: pretium_finance_assessment
description: A clean Flutter project.
publish_to: 'none'

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.3

dev_dependencies: {}

flutter:
  uses-material-design: true
  
